name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Expo CLI and EAS CLI
        run: npm install -g expo-cli eas-cli

      - name: EAS Build - APK
        run: eas build --platform android --profile production --non-interactive --output=build-url.txt
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Show APK download link
        run: cat build-url.txt

      - name: Upload download link as artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-download-link
          path: build-url.txt
